export const Constants = {
	ROLE_ADMIN: 1,
	ROLE_USER: 2,

	CURRENCY_USD: 1,
	CURRENCY_PEN: 2,

	CATEGORY_FOOD: 1,
	CATEGORY_SHOPPING: 2,
	CATEGORY_HOUSING: 3,
	CATEGORY_TRANSPORTATION: 4,
	CATEGORY_INCOME: 5,
	CATEGORY_HEALTH: 6,
	CATEGORY_OTHER: 7,

	TYPE_INCOME: 1,
	TYPE_EXPENSE: 2
}